/*
 * @Author: 1491579574@qq.com
 * @Date: 2023-08-07 18:43:57
 * @LastEditors: eastspire 1491579574@qq.com
 * @LastEditTime: 2024-01-07 23:14:07
 * @FilePath: \LTPP-CODE\Frontend\src\plugins\SqsGlobal.js
 * @Description: Email:1491579574@qq.com
 * QQ:1491579574
 * Copyright (c) 2023 by SQS, All Rights Reserved.
 */

const logo_url = '/logo.png';

/* 全局变量 */
let c_tips = window?.c_tips?.length > 0 ? window.c_tips : [''];
let cpp_tips = window?.cpp_tips?.length > 0 ? window.cpp_tips : [''];
let java_tips = window?.java_tips?.length > 0 ? window.java_tips : [''];
let golang_tips = window?.golang_tips?.length > 0 ? window.golang_tips : [''];
let javascript_tips =
  window?.javascript_tips?.length > 0 ? window.javascript_tips : [''];
let rust_tips = window?.rust_tips?.length > 0 ? window.rust_tips : [''];
let php_tips = window?.php_tips?.length > 0 ? window.php_tips : [''];
let typescript_tips =
  window?.typescript_tips?.length > 0 ? window.typescript_tips : [''];
let ruby_tips = window?.ruby_tips?.length > 0 ? window.ruby_tips : [''];
let csharp_tips = window?.csharp_tips?.length > 0 ? window.csharp_tips : [''];
let python_tips = window?.python_tips?.length > 0 ? window.python_tips : [''];

const cpp = cpp_tips[0] || '';
const c = c_tips[0] || '';
const java = java_tips[0] || '';
const python = python_tips[0] || '';
const go = golang_tips[0] || '';
const php = php_tips[0] || '';
const javascript = javascript_tips[0] || '';
const rust = rust_tips[0] || '';
const typescript = typescript_tips[0] || '';
const ruby = ruby_tips[0] || '';
const csharp = csharp_tips[0] || '';
const websocket_connect_str = '@ltpp@';
const loading_tips = '加载中';
const code_light_css =
  '--mtk1:#7c4dff !important;--mtk5:#3dc9b0 !important;--mtk6:#fa278e !important;--mtk7:#437aed !important;--mtk8:#d365e5 !important;--mtk9:#437aed !important;--mtk14:#ff0000 !important;--mtk20:#3dc9b0 !important;--mtk22:#fa278e !important;--mtk23:#3dc9b0 !important;';
const code_dark_css =
  '--mtk1:#21e016 !important;--mtk5:#3dc9b0 !important;--mtk6:#ff9070 !important;--mtk7:#ffdd00 !important;--mtk8:#fa278e !important;--mtk9:#ff9900 !important;--mtk14:#ff0000 !important;--mtk20:#3dc9b0 !important;--mtk22:#00d7ff !important;--mtk23:#00bdff !important;';

// 编辑器主题
const themelist = [
  {
    value: 'vs-dark',
    label: '暗黑主题',
    css: code_dark_css,
  },
  {
    value: 'vs',
    label: '亮色主题',
    css: code_light_css,
  },
  {
    value: 'hc-black',
    label: '暗黑高亮',
    css: code_dark_css,
  },
  {
    value: 'hc-light',
    label: '亮色高亮',
    css: code_light_css,
  },
];

const language_map = {
  c: 'C',
  cpp: 'C++',
  java: 'Java',
  python: 'Python3',
  go: 'Go',
  php: 'PHP',
  javascript: 'JavaScript',
  rust: 'Rust',
  typescript: 'TypeScript',
  csharp: 'C#',
  ruby: 'Ruby',
};

const map_language = {
  C: 'c',
  'C++': 'cpp',
  Java: 'java',
  Python3: 'python',
  Go: 'go',
  PHP: 'php',
  JavaScript: 'javascript',
  Rust: 'rust',
  TypeScript: 'typescript',
  'C#': 'csharp',
  Ruby: 'ruby',
};

const language_tips = {
  c: c_tips,
  cpp: cpp_tips,
  java: java_tips,
  python: python_tips,
  go: golang_tips,
  php: php_tips,
  javascript: javascript_tips,
  rust: rust_tips,
  typescript: typescript_tips,
  csharp: csharp_tips,
  ruby: ruby_tips,
};

const map_language_file = {
  c: 'c',
  cc: 'c',
  cpp: 'cpp',
  java: 'java',
  py: 'python',
  go: 'go',
  php: 'php',
  js: 'javascript',
  rs: 'rust',
  ts: 'typescript',
  cs: 'csharp',
  rb: 'ruby',
};

// 编辑器语言
const options = [
  {
    value: 'c',
    label: language_map.c,
  },
  {
    value: 'cpp',
    label: language_map.cpp,
  },
  {
    value: 'java',
    label: language_map.java,
  },
  {
    value: 'python',
    label: language_map.python,
  },
  {
    value: 'go',
    label: language_map.go,
  },
  {
    value: 'php',
    label: language_map.php,
  },
  {
    value: 'javascript',
    label: language_map.javascript,
  },
  {
    value: 'rust',
    label: language_map.rust,
  },
  {
    value: 'typescript',
    label: language_map.typescript,
  },
  {
    value: 'csharp',
    label: language_map.csharp,
  },
  {
    value: 'ruby',
    label: language_map.ruby,
  },
];

/**
 * 文章列表数据模板
 * @var object article_list_data
 */
const article_list_data = {
  id: '',
  name: loading_tips,
  article: loading_tips,
  image: '',
  writerid: '',
  writer: loading_tips,
  fabulous: loading_tips,
  collection: loading_tips,
  releasetime: loading_tips,
  lastchangetime: loading_tips,
};

/**
 * APP列表数据模板
 * @var object app_list_data
 */
const app_list_data = {
  id: '',
  name: loading_tips,
  user_id: loading_tips,
  opentimes: '',
  url: loading_tips,
  image: logo_url,
  content: loading_tips,
  user_name: loading_tips,
  time: loading_tips,
};

const question_list_data = {
  id: '',
  name: loading_tips,
  userid: '',
  time: loading_tips,
  answer_num: 0,
  writer: loading_tips,
  headimage: logo_url,
};
const monitor_list_data = {
  id: '',
  time: loading_tips,
  path: loading_tips,
  function: loading_tips,
  userid: loading_tips,
  name: loading_tips,
  grade: loading_tips,
  user_aid: loading_tips,
};
// OJ题库列表数据模板
const oj_problem_list_data = {
  id: '',
  problemName: loading_tips,
  problemLabe: loading_tips,
  ACNum: loading_tips,
  ALLSubmitNum: loading_tips,
  Time: loading_tips,
  Memory: loading_tips,
  problemFrom: loading_tips,
  ACpoint: 1,
  hassolve: 0,
  time: '加载中',
};

// OJ竞赛列表数据模板
const oj_contest_list_data = {
  id: '',
  name: loading_tips,
  content: loading_tips,
  begin: loading_tips,
  end: loading_tips,
  creater: loading_tips,
  allpeople: loading_tips,
  type: loading_tips,
  createrid: '',
  password: true,
};

// 题单列表数据模板
const questionsheet_list_data = {
  id: '',
  name: loading_tips,
  time: loading_tips,
  people_num: loading_tips,
  creator_name: loading_tips,
  password: true,
  creator_id: '',
};

// 服务器列表数据模板
const linux_list_data = {
  id: '',
  userid: '',
  name: loading_tips,
  end_port: loading_tips,
  begin_port: loading_tips,
  password: loading_tips,
  buy_time: loading_tips,
  user_name: loading_tips,
  cpu: loading_tips,
  memory: loading_tips,
};

const video_list_data = {
  fabulous: 0,
  id: '',
  love: 0,
  name: '加载中',
  tag: '加载中',
  url: '加载中',
  time: '加载中',
};

// 商品列表数据模板
const goods_list_data = {
  id: '',
  name: loading_tips,
  money: loading_tips,
  path: loading_tips,
  type: loading_tips,
  size: loading_tips,
  times: loading_tips,
  blurb: loading_tips,
  time: loading_tips,
  has_buy: true,
};

// 公告数据模板
const notice_list_data = {
  id: '',
  content: loading_tips,
  time: loading_tips,
};

// 用户列表数据模板
const user_list_data = {
  id: '',
  name: loading_tips,
  registertime: loading_tips,
  lastlogin: loading_tips,
  sex: loading_tips,
  email: loading_tips,
  headimage: logo_url,
  fans: loading_tips,
  follow: loading_tips,
  online: loading_tips,
  acnum: loading_tips,
  mysay: loading_tips,
  bkimage: '',
};
// 用户排名界面数据模板
const user_rank_list_data = {
  index: loading_tips,
  id: loading_tips,
  name: loading_tips,
  acnum: loading_tips,
  registertime: loading_tips,
  lastlogin: loading_tips,
  online: 0,
  sex: loading_tips,
  fans: loading_tips,
  follow: loading_tips,
};
// 提交记录数据模板
const codehistory_data = {
  id: 0,
  userid: '',
  language: loading_tips,
  status: loading_tips,
  time: loading_tips,
  usetime: 0,
  usememory: 0,
  code: loading_tips,
  user: loading_tips,
};
// 短句数据模板
const short_sentence_list = {
  id: '',
  hitokoto: loading_tips,
  from: loading_tips,
};

const max_video_retry_times = 16;

// H5属性
const attribute = [
  // HTML 标签属性
  'accept',
  'data-size',
  'data-original-format',
  '',
  'accept-charset',
  'accesskey',
  'action',
  'align',
  'alt',
  'async',
  'autocomplete',
  'autofocus',
  'autoplay',
  'bgcolor',
  'border',
  'charset',
  'checked',
  'cite',
  'class',
  'color',
  'cols',
  'colspan',
  'content',
  'contenteditable',
  'controls',
  'coords',
  'data',
  'datetime',
  'default',
  'defer',
  'dir',
  'dirname',
  'disabled',
  'download',
  'draggable',
  'dropzone',
  'enctype',
  'for',
  'form',
  'formaction',
  'headers',
  'height',
  'hidden',
  'high',
  'href',
  'hreflang',
  'http-equiv',
  'id',
  'ismap',
  'kind',
  'label',
  'lang',
  'list',
  'loop',
  'low',
  'max',
  'maxlength',
  'media',
  'method',
  'min',
  'multiple',
  'muted',
  'name',
  'novalidate',
  'open',
  'optimum',
  'pattern',
  'placeholder',
  'poster',
  'preload',
  'radiogroup',
  'readonly',
  'rel',
  'required',
  'reversed',
  'rows',
  'rowspan',
  'sandbox',
  'scope',
  'scoped',
  'selected',
  'shape',
  'size',
  'sizes',
  'span',
  'spellcheck',
  'src',
  'srcdoc',
  'srclang',
  'srcset',
  'start',
  'step',
  'style',
  'tabindex',
  'target',
  'title',
  'translate',
  'type',
  'usemap',
  'value',
  'width',
  'wrap',
  'data',
  // SVG 标签属性
  'accent-height',
  'accumulate',
  'additive',
  'data-view-component',
  'aria-hidden',
  'alignment-baseline',
  'allowReorder',
  'alphabetic',
  'amplitude',
  'arabic-form',
  'ascent',
  'attributeName',
  'attributeType',
  'azimuth',
  'baseFrequency',
  'baseline-shift',
  'bbox',
  'begin',
  'bias',
  'by',
  'calcMode',
  'cap-height',
  'clip',
  'clip-path',
  'clip-rule',
  'color',
  'color-interpolation',
  'color-interpolation-filters',
  'color-profile',
  'color-rendering',
  'contentScriptType',
  'contentStyleType',
  'crossorigin',
  'cursor',
  'cx',
  'cy',
  'd',
  'decelerate',
  'descent',
  'diffuseConstant',
  'direction',
  'display',
  'divisor',
  'dominant-baseline',
  'dur',
  'dx',
  'dy',
  'edgeMode',
  'elevation',
  'enable-background',
  'end',
  'exponent',
  'externalResourcesRequired',
  'fill',
  'fill-opacity',
  'fill-rule',
  'filter',
  'filterRes',
  'filterUnits',
  'flood-color',
  'flood-opacity',
  'font-family',
  'font-size',
  'font-size-adjust',
  'font-stretch',
  'font-style',
  'font-variant',
  'font-weight',
  'format',
  'from',
  'fr',
  'fx',
  'fy',
  'g1',
  'g2',
  'glyph-name',
  'glyph-orientation-horizontal',
  'glyph-orientation-vertical',
  'glyphRef',
  'gradientTransform',
  'gradientUnits',
  'hanging',
  'horiz-adv-x',
  'horiz-origin-x',
  'ideographic',
  'image-rendering',
  'in',
  'in2',
  'intercept',
  'k',
  'k1',
  'k2',
  'k3',
  'k4',
  'kernelMatrix',
  'kernelUnitLength',
  'kerning',
  'keyPoints',
  'keySplines',
  'keyTimes',
  'lengthAdjust',
  'letter-spacing',
  'lighting-color',
  'limitingConeAngle',
  'local',
  'marker-end',
  'marker-mid',
  'marker-start',
  'markerHeight',
  'markerUnits',
  'markerWidth',
  'mask',
  'maskContentUnits',
  'maskUnits',
  'mathematical',
  'max',
  'media',
  'method',
  'min',
  'mode',
  'name',
  'numOctaves',
  'offset',
  'onabort',
  'onactivate',
  'onbegin',
  'onclick',
  'onend',
  'onerror',
  'onfocusin',
  'onfocusout',
  'onload',
  'onmousedown',
  'onmousemove',
  'onmouseout',
  'onmouseover',
  'onmouseup',
  'onrepeat',
  'onresize',
  'onscroll',
  'onunload',
  'operator',
  'order',
  'orient',
  'orientation',
  'origin',
  'overflow',
  'overline-position',
  'overline-thickness',
  'panose-1',
  'paint-order',
  'path',
  'pathLength',
  'patternContentUnits',
  'patternTransform',
  'patternUnits',
  'pointer-events',
  'points',
  'pointsAtX',
  'pointsAtY',
  'pointsAtZ',
  'preserveAlpha',
  'preserveAspectRatio',
  'primitiveUnits',
  'r',
  'radius',
  'referrerPolicy',
  'refX',
  'refY',
  'rel',
  'repeatCount',
  'repeatDur',
  'requiredExtensions',
  'requiredFeatures',
  'restart',
  'result',
  'rotate',
  'rx',
  'ry',
  'scale',
  'seed',
  'shape-rendering',
  'slope',
  'spacing',
  'specularConstant',
  'specularExponent',
  'speed',
  'spreadMethod',
  'startOffset',
  'stdDeviation',
  'stemh',
  'stemv',
  'stitchTiles',
  'stop-color',
  'stop-opacity',
  'strikethrough-position',
  'strikethrough-thickness',
  'string',
  'stroke',
  'stroke-dasharray',
  'stroke-dashoffset',
  'stroke-linecap',
  'stroke-linejoin',
  'stroke-miterlimit',
  'stroke-opacity',
  'stroke-width',
  'surfaceScale',
  'systemLanguage',
  'tabindex',
  'tableValues',
  'targetX',
  'targetY',
  'text-anchor',
  'text-decoration',
  'text-rendering',
  'textLength',
  'to',
  'transform',
  'type',
  'u1',
  'u2',
  'underline-position',
  'underline-thickness',
  'unicode',
  'unicode-bidi',
  'unicode-range',
  'units-per-em',
  'v-alphabetic',
  'v-hanging',
  'v-ideographic',
  'v-mathematical',
  'values',
  'vector-effect',
  'version',
  'vert-adv-y',
  'vert-origin-x',
  'vert-origin-y',
  'viewBox',
  'viewTarget',
  'visibility',
  'widths',
  'word-spacing',
  'writing-mode',
  'x',
  'x-height',
  'x1',
  'x2',
  'xChannelSelector',
  'xlink:actuate',
  'xlink:arcrole',
  'xlink:href',
  'xlink:role',
  'xlink:show',
  'xlink:title',
  'xlink:type',
  'xml:base',
  'xml:lang',
  'xml:space',
  'y',
  'y1',
  'y2',
  'yChannelSelector',
  'z',
  'zoomAndPan',
  'xmlns',
  // WebView 和 iFrame 属性
  'allow',
  'allowfullscreen',
  'allowpaymentrequest',
  'allowusermedia',
  'csp',
  'height',
  'loading',
  'name',
  'referrerpolicy',
  'sandbox',
  'srcdoc',
  'width',
];

/**
 * @var object extion_map_number 文件类型转数字
 */
const extion_map_number = {
  mp3: 2,
  aac: 2,
  ac3: 2,
  mp3adu: 2,
  mp3adufloat: 2,
  mp3float: 2,
  mp3on4: 2,
  mp3on4float: 2,
  amrnb: 2,
  amrwb: 2,
  cook: 2,
  ra_144: 2,
  ra_288: 2,
  sipr: 2,
  wmav1: 2,
  wmav2: 2,
  wmavoice: 2,
  wmapro: 2,
  wamlossless: 2,
  nellymoser: 2,
  vorbis: 2,
  m3u8: 2,
  mp4: 3,
  avi: 3,
  rmvb: 3,
  '3gp': 3,
  mpeg: 3,
  wmv: 3,
  mov: 3,
  mpv: 3,
  flv: 3,
  swf: 3,
  cpp: 4,
  c: 4,
  js: 4,
  html: 4,
  css: 4,
  php: 4,
  go: 4,
  java: 4,
  py: 4,
  ts: 4,
  json: 4,
  gitignore: 4,
  sh: 4,
  lock: 4,
  rs: 4,
  dart: 4,
  cs: 4,
  r: 4,
  pdf: 5,
  rar: 6,
  zip: 6,
  tar: 6,
  gz: 6,
  'tar.gz': 6,
  '7z': 6,
  apz: 6,
  ar: 6,
  bz: 6,
  car: 6,
  dar: 6,
  cpgz: 6,
  f: 6,
  ha: 6,
  hbcj: 6,
  hbc2j: 6,
  hbej: 6,
  hpkj: 6,
  hypj: 6,
  jpg: 7,
  png: 7,
  jpeg: 7,
  gif: 7,
  svg: 7,
  bmp: 7,
  tif: 7,
  pcx: 7,
  tga: 7,
  exif: 7,
  fpx: 7,
  psd: 7,
  cdr: 7,
  pcd: 7,
  dxf: 7,
  ufo: 7,
  eps: 7,
  ai: 7,
  raw: 7,
  WMF: 7,
  webp: 7,
  avif: 7,
  apng: 7,
  exe: 8,
  apk: 8,
  bat: 8,
  ace: 8,
  app: 8,
  com: 8,
};

// 标签白名单，均会转小写，所以只需要配置小写规则
const white_list = {
  a: attribute,
  div: attribute,
  img: attribute,
  p: attribute,
  span: attribute,
  h1: attribute,
  h2: attribute,
  h3: attribute,
  h4: attribute,
  h5: attribute,
  h6: attribute,
  code: attribute,
  blockquote: attribute,
  button: attribute,
  hr: attribute,
  ul: attribute,
  ol: attribute,
  li: attribute,
  table: attribute,
  tr: attribute,
  td: attribute,
  th: attribute,
  form: attribute,
  input: attribute,
  textarea: attribute,
  label: attribute,
  select: attribute,
  option: attribute,
  iframe: attribute,
  canvas: attribute,
  audio: attribute,
  video: attribute,
  abbr: attribute,
  address: attribute,
  b: attribute,
  bdi: attribute,
  bdo: attribute,
  big: attribute,
  center: attribute,
  cite: attribute,
  del: attribute,
  dfn: attribute,
  em: attribute,
  font: attribute,
  i: attribute,
  ins: attribute,
  kbd: attribute,
  mark: attribute,
  meter: attribute,
  output: attribute,
  progress: attribute,
  q: attribute,
  rp: attribute,
  rt: attribute,
  ruby: attribute,
  s: attribute,
  samp: attribute,
  small: attribute,
  strike: attribute,
  strong: attribute,
  sub: attribute,
  sup: attribute,
  template: attribute,
  time: attribute,
  tt: attribute,
  u: attribute,
  var: attribute,
  wbr: attribute,
  svg: attribute,
  body: attribute,
  html: attribute,
  path: attribute,
  meta: attribute,
  title: attribute,
  '!doctype html': attribute,
  '!doctype': attribute,
  source: attribute,
  pre: attribute,
  linearGradient: attribute,
  stop: attribute,
  br: attribute,
  figure: attribute,
  head: attribute,
  ifream: attribute,
  webview: attribute,
  details: attribute,
  summary: attribute,
};

// xss配置
const xss_options = {
  whiteList: white_list,
};

// 去掉不在白名单上的标签
const strip_ignore_tag_body = true;

const no_support_file_tips = '该资源暂不支持预览';

const root_name = 'root';

const redirect_url_key = 'redirect_url';

export default {
  root_name,
  logo_url,
  no_support_file_tips,
  extion_map_number,
  strip_ignore_tag_body,
  xss_options,
  loading_tips,
  websocket_connect_str,
  language_map,
  map_language,
  map_language_file,
  language_tips,
  cpp,
  c,
  java,
  python,
  go,
  php,
  javascript,
  rust,
  csharp,
  ruby,
  typescript,
  redirect_url_key,
  // 编辑器主题
  themelist,
  // 编辑器语言
  options,
  // 文章列表数据模板
  article_list_data,
  // OJ题库列表数据模板
  oj_problem_list_data,
  // OJ竞赛列表数据模板
  oj_contest_list_data,
  // 用户列表数据模板
  user_list_data,
  // 用户排名界面数据模板
  user_rank_list_data,
  // 提交记录数据模板
  codehistory_data,
  // 短句数据模板
  short_sentence_list,
  // 商品数据模板
  goods_list_data,
  max_video_retry_times,
  video_list_data,
  question_list_data,
  monitor_list_data,
  notice_list_data,
  questionsheet_list_data,
  linux_list_data,
  app_list_data,
};
